apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kubernetes
  namespace: vallegrande
spec:
  selector:
    matchLabels:
      app: spring-boot-kubernetes
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes
    spec:
      containers:
        - name: spring-boot-kubernetes
          image: springboot-kubernetes:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
