apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes
  namespace: vallegrande
spec:
  selector:
    app: spring-boot-kubernetes
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort